<?php
use Grafema\I18n;

/**
 * Form for create & edit emails.
 *
 * @since 2025.1
 */
Dashboard\Form::enqueue(
	'grafema-emails-creator',
	[
		'class'          => 'dg g-6 p-6',
		'@submit.window' => '$ajax("import-email")',
	],
	[
		[
			'type'        => 'text',
			'name'        => 'title',
			'label'       => I18n::_t( 'Email heading' ),
			'class'       => '',
			'label_class' => 'df aic fs-12 t-muted',
			'reset'       => 0,
			'before'      => '',
			'after'       => '',
			'instruction' => '',
			'tooltip'     => '',
			'copy'        => 0,
			'sanitizer'   => '',
			'validator'   => '',
			'conditions'  => [],
			'attributes'  => [
				'value'       => '',
				'required'    => true,
				'placeholder' => I18n::_t( 'Email heading' ),
			],
		],
		[
			'type'        => 'select',
			'name'        => 'event',
			'label'       => I18n::_t( 'Events' ),
			'class'       => '',
			'label_class' => 'df aic fs-12 t-muted',
			'reset'       => 0,
			'before'      => '',
			'after'       => '',
			'instruction' => '',
			'tooltip'     => '',
			'copy'        => 0,
			'sanitizer'   => '',
			'validator'   => '',
			'conditions'  => [],
			'attributes'  => [
				'value'    => '',
				'required' => true,
			],
			'options' => [
				''                => I18n::_t( 'Select an event' ),
				'user-registered' => I18n::_t( 'New user registered' ),
			],
		],
		[
			'type'        => 'text',
			'name'        => 'subtitle',
			'label'       => I18n::_t( 'Subtitle' ),
			'class'       => '',
			'label_class' => 'df aic fs-12 t-muted',
			'reset'       => 0,
			'before'      => '',
			'after'       => '',
			'instruction' => '',
			'tooltip'     => '',
			'copy'        => 0,
			'sanitizer'   => '',
			'validator'   => '',
			'conditions'  => [],
			'attributes'  => [
				'required'    => true,
				'placeholder' => I18n::_t( 'Subtitle' ),
			],
		],
		[
			'type'        => 'textarea',
			'name'        => 'content',
			'label'       => I18n::_t( 'Content' ),
			'class'       => '',
			'label_class' => 'df aic fs-12 t-muted',
			'reset'       => 0,
			'before'      => '',
			'after'       => '',
			'instruction' => I18n::_t( 'Enter recipients for this email. Each recipient email from a new line.' ),
			'tooltip'     => '',
			'copy'        => 0,
			'sanitizer'   => '',
			'validator'   => '',
			'conditions'  => [],
			'attributes'  => [
				'value'       => '',
				'rows'        => 5,
				'required'    => true,
				'placeholder' => I18n::_t( 'N/A' ),
			],
		],
		[
			'type'        => 'textarea',
			'name'        => 'recipients',
			'label'       => I18n::_t( 'Recipient(s)' ),
			'class'       => '',
			'label_class' => 'df aic fs-12 t-muted',
			'reset'       => 0,
			'before'      => '',
			'after'       => '',
			'instruction' => I18n::_t( 'Enter recipients for this email. Each recipient email from a new line.' ),
			'tooltip'     => '',
			'copy'        => 0,
			'sanitizer'   => '',
			'validator'   => '',
			'conditions'  => [],
			'attributes'  => [
				'value'       => '',
				'required'    => true,
				'placeholder' => I18n::_t( 'N/A' ),
			],
		],
	]
);