<?php
use Grafema\I18n;
use Grafema\Url;
use Grafema\Sanitizer;

/**
 * Form for create & edit posts.
 *
 * @since 2025.1
 */
Dashboard\Form::enqueue(
	'grafema-posts-creator',
	[
		'x-data'          => sprintf( "tab('%s')", Sanitizer::prop( $_GET['tab'] ?? 'main' ) ),
		'@submit.prevent' => '$ajax("posts/update")',
	],
	[
		[
			'type'        => 'image',
			'name'        => 'avatar',
			'label'       => I18n::_t( 'Upload avatar' ),
			'class'       => 'dg p-6 pb-3 bg-gray-lt',
			'label_class' => '',
			'reset'       => 0,
			'before'      => '',
			'after'       => '',
			'instruction' => I18n::_t( 'Click to upload or drag & drop' ),
			'tooltip'     => '',
			'copy'        => 0,
			'sanitizer'   => '',
			'validator'   => '',
			'conditions'  => [],
			'attributes'  => [
				'value'    => '',
				'required' => false,
				'@change'  => '[...$refs.uploader.files].map(file => $ajax("upload/media").then(response => files.unshift(response[0])))',
			],
		],
		[
			'name'          => 'main',
			'type'          => 'tab',
			'label'         => I18n::_t( 'General' ),
			'description'   => '',
			'icon'          => 'ph ph-pen',
			'class_menu'    => 'bg-gray-lt',
			'class_button'  => 'ml-7',
			'class_content' => 'p-7',
			'fields'        => [
				[
					'type'          => 'group',
					'name'          => 'excerpt',
					'label'         => I18n::_t( 'Title' ),
					'class'         => '',
					'label_class'   => 'ga-1 fs-12 t-muted',
					'content_class' => 'dg ga-4 g-7 gtc-1',
					'fields'        => [
						[
							'type'        => 'textarea',
							'name'        => 'title',
							'label'       => '',
							'class'       => '',
							'label_class' => '',
							'reset'       => 0,
							'before'      => '',
							'after'       => '',
							'instruction' => '',
							'tooltip'     => '',
							'copy'        => 0,
							'sanitizer'   => '',
							'validator'   => '',
							'conditions'  => [],
							'attributes'  => [
								'rows'        => 1,
								'required'    => true,
								'placeholder' => I18n::_t( 'Add title...' ),
							],
						],
						[
							'type'        => 'text',
							'name'        => 'permalink',
							'label'       => '',
							'class'       => '',
							'label_class' => '',
							'reset'       => 0,
							'before'     => sprintf( '<code class="badge">%s</code>', Url::site() ),
							'after'       => '',
							'instruction' => '',
							'tooltip'     => '',
							'copy'        => 0,
							'sanitizer'   => '',
							'validator'   => '',
							'conditions'  => [],
							'attributes'  => [
								'required' => true,
							],
						],
					],
				],
				[
					'type'          => 'group',
					'name'          => 'excerpt',
					'label'         => I18n::_t( 'Excerpt' ),
					'class'         => '',
					'label_class'   => 'ga-1 fs-12 t-muted',
					'content_class' => 'dg ga-4 g-7 gtc-1',
					'fields'        => [
						[
							'type'        => 'textarea',
							'name'        => 'excerpt',
							'label'       => '',
							'class'       => '',
							'label_class' => '',
							'reset'       => 0,
							'before'      => '',
							'after'       => '',
							'instruction' => I18n::_t( 'This section only applicable to post types that have excerpts enabled. Here you can write a one to two sentence description of the post.' ),
							'tooltip'     => '',
							'copy'        => 0,
							'sanitizer'   => '',
							'validator'   => '',
							'conditions'  => [],
							'attributes'  => [
								'rows'        => 1,
								'value'       => '',
								'placeholder' => I18n::_t( 'Write an excerpt (optional)...' ),
							],
						],
					],
				],
				[
					'type'          => 'group',
					'name'          => 'summary',
					'label'         => I18n::_t( 'Visibility & status' ),
					'class'         => '',
					'label_class'   => 'ga-1 fs-12 t-muted',
					'content_class' => '',
					'fields'        => [
						[
							'type'        => 'select',
							'name'        => 'status',
							'label'       => '',
							'class'       => '',
							'label_class' => '',
							'reset'       => 0,
							'before'      => '',
							'after'       => '',
							'instruction' => '',
							'tooltip'     => '',
							'copy'        => 0,
							'sanitizer'   => '',
							'validator'   => '',
							'conditions'  => [],
							'attributes'  => [
								'value' => 'publish',
							],
							'options' => [
								'publish' => I18n::_t( 'Publish' ),
								'pending' => I18n::_t( 'Pending' ),
								'draft'   => I18n::_t( 'Draft' ),
							],
						],
						[
							'type'        => 'select',
							'name'        => 'visibility',
							'label'       => '',
							'class'       => '',
							'label_class' => '',
							'reset'       => 0,
							'before'      => '',
							'after'       => '',
							'instruction' => '',
							'tooltip'     => '',
							'copy'        => 0,
							'sanitizer'   => '',
							'validator'   => '',
							'conditions'  => [],
							'attributes'  => [
								'value' => 'public',
							],
							'options' => [
								'public'  => I18n::_t( 'Public' ),
								'private' => I18n::_t( 'Private' ),
								'pending' => I18n::_t( 'Password protected' ),
							],
						],
					],
				],
				[
					'type'          => 'group',
					'name'          => 'dates',
					'label'         => I18n::_t( 'Publication dates' ),
					'class'         => '',
					'label_class'   => 'ga-1 fs-12 t-muted',
					'content_class' => '',
					'fields'        => [
						[
							'type'        => 'date',
							'name'        => 'from',
							'label'       => '',
							'class'       => '',
							'label_class' => '',
							'reset'       => 0,
							'before'      => I18n::_f( '%sFrom:%s', '<samp class="badge badge--blue-lt">', '</samp>' ),
							'after'       => '',
							'instruction' => '',
							'tooltip'     => '',
							'copy'        => 0,
							'sanitizer'   => '',
							'validator'   => '',
							'conditions'  => [],
							'attributes'  => [
								'placeholder' => I18n::_t( 'e.g. Just another Grafema site' ),
							],
						],
						[
							'type'        => 'date',
							'name'        => 'to',
							'label'       => '',
							'class'       => '',
							'label_class' => '',
							'reset'       => 0,
							'before'      => I18n::_f( '%sTo:%s', '<samp class="badge badge--blue-lt">', '</samp>' ),
							'after'       => '',
							'instruction' => '',
							'tooltip'     => '',
							'copy'        => 0,
							'sanitizer'   => '',
							'validator'   => '',
							'conditions'  => [],
							'attributes'  => [
								'placeholder' => I18n::_t( 'e.g. Just another Grafema site' ),
							],
						],
					],
				],
				[
					'type'          => 'group',
					'name'          => 'authors',
					'label'         => I18n::_t( 'Authors' ),
					'class'         => '',
					'label_class'   => 'ga-1 fs-12 t-muted',
					'content_class' => 'dg ga-4 g-7 gtc-1',
					'fields'        => [
						[
							'type'        => 'select',
							'name'        => 'language',
							'label'       => '',
							'class'       => '',
							'label_class' => '',
							'reset'       => 0,
							'before'      => '',
							'after'       => '',
							'instruction' => '',
							'tooltip'     => '',
							'copy'        => 0,
							'sanitizer'   => '',
							'validator'   => '',
							'conditions'  => [],
							'attributes'  => [
								'value'    => 'us',
								'required' => true,
								'multiple' => true,
							],
							'options' => [
								'us' => [
									'image'   => 'assets/images/flags/us.svg',
									'content' => I18n::_t( 'English - english' ),
								],
								'ru' => [
									'image'   => 'assets/images/flags/ru.svg',
									'content' => I18n::_t( 'Russian - русский' ),
								],
								'he' => [
									'image'   => 'assets/images/flags/il.svg',
									'content' => I18n::_t( 'עִבְרִית - Hebrew' ),
								],
							],
						],
					],
				],
			],
		],
		[
			'name'          => 'comments',
			'type'          => 'tab',
			'label'         => I18n::_t( 'Comments' ),
			'description'   => '',
			'icon'          => 'ph ph-chats',
			'class_button'  => '',
			'class_content' => 'p-7',
			'fields'        => [
				[
					'type'          => 'group',
					'name'          => 'discussion',
					'label'         => I18n::_t( 'Discussion' ),
					'class'         => '',
					'label_class'   => 'ga-1 fs-12 t-muted',
					'content_class' => '',
					'fields'        => [
						[
							'type'        => 'select',
							'name'        => 'discussion',
							'label'       => '',
							'class'       => '',
							'label_class' => '',
							'reset'       => 0,
							'before'      => '',
							'after'       => '',
							'instruction' => '',
							'tooltip'     => '',
							'copy'        => 0,
							'sanitizer'   => '',
							'validator'   => '',
							'conditions'  => [],
							'attributes'  => [],
							'options' => [
								'open'        => I18n::_t( 'Open' ),
								'close'       => I18n::_t( 'Close' ),
								'temporarily' => I18n::_t( 'Temporarily' ),
							],
						],
					],
				],
			],
		],
	]
);