<?php
/**
 * This file is part of Grafema CMS.
 *
 * @link     https://www.grafema.io
 * @contact  team@core.io
 * @license  https://github.com/grafema-team/grafema/LICENSE.md
 */
namespace Dashboard;

use Grafema\I18n;
use Grafema\Patterns\Registry;
use Grafema\Patterns\Singleton;

/**
 * Set dashboard constants.
 */
final class Constants
{
	use Singleton;

	/**
	 * Class constructor.
	 *
	 * @since 1.0.0
	 */
	public function __construct()
	{
		Registry::set(
			'images',
			[
				'thumbnail' => [
					'name'   => I18n::__( 'Thumbnail' ),
					'width'  => 240,
					'height' => 240,
				],
			]
		);

		Registry::set(
			'timezones',
			[
				'Pacific/Midway'                 => '-11:00, Midway, Midway Time',
				'Pacific/Niue'                   => '-11:00, Niue, Niue Time',
				'Pacific/Pago_Pago'              => '-11:00, Pago_Pago, American Samoa Time',
				'Pacific/Honolulu'               => '-10:00, Honolulu, HST',
				'Pacific/Rarotonga'              => '-10:00, Rarotonga, Cook Islands Time',
				'Pacific/Marquesas'              => '-09:30, Marquesas',
				'Pacific/Gambier'                => '-09:00, Gambier',
				'America/Anchorage'              => '-08:00, Anchorage, AKT',
				'America/Juneau'                 => '-08:00, Juneau, AKT',
				'America/Metlakatla'             => '-08:00, Metlakatla, AKT',
				'America/Nome'                   => '-08:00, Nome, AKT',
				'America/Sitka'                  => '-08:00, Sitka, AKT',
				'America/Yakutat'                => '-08:00, Yakutat, AKT',
				'America/Creston'                => '-07:00, Creston, MST',
				'America/Dawson'                 => '-07:00, Dawson, PT',
				'America/Fort_Nelson'            => '-07:00, Fort Nelson, MST',
				'America/Hermosillo'             => '-07:00, Hermosillo',
				'America/Los_Angeles'            => '-07:00, Los Angeles, PT',
				'America/Phoenix'                => '-07:00, Phoenix, MST',
				'America/Vancouver'              => '-07:00, Vancouver, PT',
				'America/Whitehorse'             => '-07:00, Whitehorse, PT',
				'America/Belize'                 => '-06:00, Belize, CST',
				'America/Boise'                  => '-06:00, Boise, MT',
				'America/Cambridge_Bay'          => '-06:00, Cambridge Bay, MT',
				'America/Chihuahua'              => '-06:00, Chihuahua',
				'America/Costa_Rica'             => '-06:00, Costa Rica',
				'America/Denver'                 => '-06:00, Denver, MT',
				'America/Edmonton'               => '-06:00, Edmonton, MT',
				'America/El_Salvador'            => '-06:00, El Salvador',
				'America/Guatemala'              => '-06:00, Guatemala',
				'America/Inuvik'                 => '-06:00, Inuvik, MT',
				'America/Managua'                => '-06:00, Managua, hora de Nicaragua',
				'America/Mazatlan'               => '-06:00, Mazatlan, hora de Mazatlán',
				'America/Ojinaga'                => '-06:00, Ojinaga, hora de Ojinaga',
				'America/Regina'                 => '-06:00, Regina, CST',
				'America/Tegucigalpa'            => '-06:00, Tegucigalpa, hora de Honduras',
				'America/Yellowknife'            => '-06:00, Yellowknife, MT',
				'Pacific/Easter'                 => '-06:00, Easter, hora de Isla de Pascua',
				'Pacific/Galapagos'              => '-06:00, Galapagos, hora de Galápagos',
				'America/Atikokan'               => '-05:00, Atikokan, EST',
				'America/Bahia_Banderas'         => '-05:00, Bahia_Banderas, hora de Bahía de Banderas',
				'America/Bogota'                 => '-05:00, Bogota, hora de Colombia',
				'America/Cancun'                 => '-05:00, Cancun, hora de Cancún',
				'America/Chicago'                => '-05:00, Chicago, CT',
				'America/Eirunepe'               => '-05:00, Eirunepe, ACT',
				'America/Guayaquil'              => '-05:00, Guayaquil, hora de Ecuador',
				'America/Jamaica'                => '-05:00, Jamaica, EST',
				'America/Lima'                   => '-05:00, Lima, hora de Perú',
				'America/Matamoros'              => '-05:00, Matamoros, hora de Matamoros',
				'America/Menominee'              => '-05:00, Menominee, CT',
				'America/Merida'                 => '-05:00, Merida, hora de Mérida',
				'America/Mexico_City'            => '-05:00, Mexico_City, hora de Ciudad de México',
				'America/Monterrey'              => '-05:00, Monterrey, hora de Monterrey',
				'America/Panama'                 => '-05:00, Panama, Panamá',
				'America/Resolute'               => '-05:00, Resolute, CT',
				'America/Rio_Branco'             => '-05:00, Rio_Branco, ACT',
				'America/Winnipeg'               => '-05:00, Winnipeg, CT',
				'America/Anguilla'               => '-04:00, Anguilla, AST',
				'America/Antigua'                => '-04:00, Antigua, AST',
				'America/Aruba'                  => '-04:00, Aruba, AST',
				'America/Asuncion'               => '-04:00, Asuncion, Paraguay Time',
				'America/Barbados'               => '-04:00, Barbados, AST',
				'America/Campo_Grande'           => '-04:00, Campo_Grande, AMT',
				'America/Caracas'                => '-04:00, Caracas, Venezuela Time',
				'America/Cuiaba'                 => '-04:00, Cuiaba, AMT',
				'America/Curacao'                => '-04:00, Curacao, AST',
				'America/Detroit'                => '-04:00, Detroit, ET',
				'America/Dominica'               => '-04:00, Dominica, AST',
				'America/Grand_Turk'             => '-04:00, Grand_Turk, ET',
				'America/Grenada'                => '-04:00, Grenada, AST',
				'America/Guadeloupe'             => '-04:00, Guadeloupe, AST',
				'America/Guyana'                 => '-04:00, Guyana, Guyana Time',
				'America/Havana'                 => '-04:00, Havana, Cuba Time',
				'America/Iqaluit'                => '-04:00, Iqaluit, ET',
				'America/La_Paz'                 => '-04:00, La_Paz, BO',
				'America/Lower_Princes'          => '-04:00, Lower_Princes, AST',
				'America/Martinique'             => '-04:00, Martinique, AST',
				'America/Nassau'                 => '-04:00, Nassau, Bahami',
				'America/New_York'               => '-04:00, New York, ET',
				'America/Puerto_Rico'            => '-04:00, Puerto Rico, AST',
				'America/Santiago'               => '-04:00, Santiago, hora de Chile',
				'America/Santo_Domingo'          => '-04:00, Santo Domingo, AST',
				'America/Thunder_Bay'            => '-04:00, Thunder_Bay, ET',
				'America/Toronto'                => '-04:00, Toronto, ET',
				'America/Tortola'                => '-04:00, Tortola, AST',
				'America/Araguaina'              => '-03:00, Araguaina, BRT',
				'America/Argentina/Buenos_Aires' => '-03:00, Buenos Aires',
				'America/Halifax'                => '-03:00, Halifax, AT',
				'America/Maceio'                 => '-03:00, Maceio, BRT',
				'America/Montevideo'             => '-03:00, Montevideo, Uruguay Time',
				'America/Recife'                 => '-03:00, Recife, BRT',
				'America/Santarem'               => '-03:00, Santarem, BRT',
				'America/Sao_Paulo'              => '-03:00, Sao_Paulo, BRT',
				'America/Thule'                  => '-03:00, Thule, Horario de: Thule',
				'America/St_Johns'               => '-02:30, St_Johns, St. John’s Time',
				'America/Miquelon'               => '-02:00, Miquelon, St. Pierre & Miquelon Time',
				'America/Noronha'                => '-02:00, Noronha, Horário Fernando de Noronha',
				'America/Nuuk'                   => '-02:00, Nuuk, America/Nuuk',
				'Atlantic/Cape_Verde'            => '-01:00, Cape Verde',
				'Africa/Freetown'                => '-00:53, Freetown, Sierra Leone čas',
				'Africa/Abidjan'                 => '+00:00, Abidjan, GMT',
				'Africa/Accra'                   => '+00:00, Accra, GMT',
				'Africa/Bamako'                  => '+00:00, Bamako',
				'Africa/Dakar'                   => '+00:00, Dakar, Senegal',
				'Atlantic/Azores'                => '+00:00, Azores, Horário Açores',
				'Atlantic/Reykjavik'             => '+00:00, Reykjavik, Ísland',
				'Africa/Algiers'                 => '+01:00, Algiers, الجزائر',
				'Africa/Casablanca'              => '+01:00, Casablanca, Morocco Time',
				'Africa/Douala'                  => '+01:00, Douala, Cameroon Time',
				'Africa/El_Aaiun'                => '+01:00, El Aaiun, Western Sahara Time',
				'Africa/Kinshasa'                => '+01:00, Kinshasa, Kinshasa Time',
				'Africa/Lagos'                   => '+01:00, Lagos, Nigeria Time',
				'Africa/Libreville'              => '+01:00, Libreville, an Ghabúin',
				'Africa/Luanda'                  => '+01:00, Luanda, Angola Time',
				'Africa/Malabo'                  => '+01:00, Malabo, Equatorial Guinea Time',
				'Africa/Ndjamena'                => '+01:00, Ndjamena, Chad Time',
				'Africa/Porto-Novo'              => '+01:00, Porto Novo, Benin Time',
				'Africa/Tunis'                   => '+01:00, Tunis, Tunisia Time',
				'Europe/Dublin'                  => '+01:00, Dublin, Ireland Time',
				'Europe/Guernsey'                => '+01:00, Guernsey, Guernsey Time',
				'Europe/Isle_of_Man'             => '+01:00, Isle_of_Man, Isle of Man Time',
				'Europe/Jersey'                  => '+01:00, Jersey, Jersey Time',
				'Europe/Lisbon'                  => '+01:00, Lisbon, Horário Portugal',
				'Europe/London'                  => '+01:00, London, UK',
				'Africa/Cairo'                   => '+02:00, Cairo, Egypt Time',
				'Africa/Gaborone'                => '+02:00, Gaborone, Botswana Time',
				'Africa/Harare'                  => '+02:00, Harare, Zimbabwe Time',
				'Africa/Johannesburg'            => '+02:00, Johannesburg, South Africa Time',
				'Africa/Kigali'                  => '+02:00, Kigali, U Rwanda',
				'Africa/Lubumbashi'              => '+02:00, Lubumbashi, Lubumbashi Time',
				'Africa/Lusaka'                  => '+02:00, Lusaka, Zambia Time',
				'Africa/Maputo'                  => '+02:00, Maputo, Mozambique Time',
				'Africa/Maseru'                  => '+02:00, Maseru, Lesotho Time',
				'Africa/Mbabane'                 => '+02:00, Mbabane, Eswatini Time',
				'Africa/Tripoli'                 => '+02:00, Tripoli, Libya Time',
				'Africa/Windhoek'                => '+02:00, Windhoek, Namibia Time',
				'Europe/Amsterdam'               => '+02:00, Amsterdam, CET',
				'Europe/Andorra'                 => '+02:00, Andorra, Andorra Time',
				'Europe/Belgrade'                => '+02:00, Belgrade, Београд',
				'Europe/Berlin'                  => '+02:00, Berlin, MEZ',
				'Europe/Bratislava'              => '+02:00, Bratislava, SEČ',
				'Europe/Brussels'                => '+02:00, Brussels, Brussel',
				'Europe/Budapest'                => '+02:00, Budapest, CET',
				'Europe/Copenhagen'              => '+02:00, Copenhagen, Denmark Time',
				'Europe/Gibraltar'               => '+02:00, Gibraltar, Gibraltar Time',
				'Europe/Kaliningrad'             => '+02:00, Kaliningrad, Калининград',
				'Europe/Ljubljana'               => '+02:00, Ljubljana, Slovenija čas',
				'Europe/Luxembourg'              => '+02:00, Luxembourg, Likisambulu',
				'Europe/Madrid'                  => '+02:00, Madrid, CET',
				'Europe/Malta'                   => '+02:00, Malta, CET',
				'Europe/Monaco'                  => '+02:00, Monaco, Monaco Time',
				'Europe/Oslo'                    => '+02:00, Oslo, CET',
				'Europe/Paris'                   => '+02:00, Paris, France',
				'Europe/Prague'                  => '+02:00, Prague, Praha',
				'Europe/Rome'                    => '+02:00, Rome, CET',
				'Europe/Sarajevo'                => '+02:00, Sarajevo, Bosnia & Herzegovina Time',
				'Europe/Skopje'                  => '+02:00, Skopje, CET',
				'Europe/Stockholm'               => '+02:00, Stockholm, CET',
				'Europe/Tirane'                  => '+02:00, Tirane, Albania Time',
				'Europe/Vaduz'                   => '+02:00, Vaduz, Liechtenstein Time',
				'Europe/Vatican'                 => '+02:00, Vatican, Vatican City Time',
				'Europe/Vienna'                  => '+02:00, Vienna, Austria Time',
				'Europe/Warsaw'                  => '+02:00, Warsaw, CET',
				'Europe/Zagreb'                  => '+02:00, Zagreb, CET',
				'Europe/Zurich'                  => '+02:00, Zurich, Switzerland Time',
				'Africa/Addis_Ababa'             => '+03:00, Addis Ababa',
				'Africa/Asmara'                  => '+03:00, Asmara, Eritrea Time',
				'Africa/Djibouti'                => '+03:00, Djibouti, Djibouti Time',
				'Africa/Mogadishu'               => '+03:00, Mogadishu, Waqtiga Soomaaliya',
				'Africa/Nairobi'                 => '+03:00, Nairobi, Kenya Time',
				'Asia/Aden'                      => '+03:00, Aden, Yemen Time',
				'Asia/Amman'                     => '+03:00, Amman, Jordan Time',
				'Asia/Baghdad'                   => '+03:00, Baghdad, Iraq Time',
				'Asia/Bahrain'                   => '+03:00, Bahrain, Bahrain Time',
				'Asia/Beirut'                    => '+03:00, Beirut, Libanon Zäit',
				'Asia/Damascus'                  => '+03:00, Damascus, Syria Time',
				'Asia/Jerusalem'                 => '+03:00, Jerusalem, ירושלים',
				'Asia/Kuwait'                    => '+03:00, Kuwait, KW',
				'Asia/Nicosia'                   => '+03:00, Nicosia, EET',
				'Asia/Qatar'                     => '+03:00, Qatar, Qatar Time',
				'Europe/Athens'                  => '+03:00, Athens, Αθήνα',
				'Europe/Bucharest'               => '+03:00, Bucharest, EET',
				'Europe/Chisinau'                => '+03:00, Chisinau, Moldova Time',
				'Europe/Helsinki'                => '+03:00, Helsinki, aikavyöhyke: Suomi',
				'Europe/Istanbul'                => '+03:00, Istanbul, Türkiye Saati',
				'Europe/Kyiv'                    => '+03:00, Kyiv, Київ',
				'Europe/Minsk'                   => '+03:00, Minsk, Минск',
				'Europe/Moscow'                  => '+03:00, Moscow, Москва',
				'Europe/Sofia'                   => '+03:00, Sofia, България',
				'Asia/Tehran'                    => '+03:30, Tehran, زمان ایران',
				'Asia/Baku'                      => '+04:00, Baku, Azərbaycan Vaxtı',
				'Asia/Dubai'                     => '+04:00, Dubai, دبي',
				'Asia/Tbilisi'                   => '+04:00, Tbilisi, თბილისი',
				'Asia/Yerevan'                   => '+04:00, Yerevan, Երևան',
				'Europe/Samara'                  => '+04:00, Samara, Самара',
				'Indian/Mahe'                    => '+04:00, Mahe, Seychelles Time',
				'Indian/Mauritius'               => '+04:00, Mauritius, Mauritius Time',
				'Indian/Reunion'                 => '+04:00, Reunion, Réunion Time',
				'Asia/Kabul'                     => '+04:30, Kabul, Afganistan-tyd',
				'Asia/Aqtau'                     => '+05:00, Aqtau, Aqtau Time',
				'Asia/Aqtobe'                    => '+05:00, Aqtobe, Aqtobe Time',
				'Asia/Ashgabat'                  => '+05:00, Ashgabat, Turkmenistan Time',
				'Asia/Atyrau'                    => '+05:00, Atyrau, Atyrau Time',
				'Asia/Dushanbe'                  => '+05:00, Dushanbe, Tajikistan Time',
				'Asia/Karachi'                   => '+05:00, Karachi, Pakistan Time',
				'Asia/Qyzylorda'                 => '+05:00, Qyzylorda, Qyzylorda Time',
				'Asia/Samarkand'                 => '+05:00, Samarkand, Samarqand',
				'Asia/Tashkent'                  => '+05:00, Tashkent, Oʻzbekiston',
				'Asia/Yekaterinburg'             => '+05:00, Yekaterinburg, Екатеринбург',
				'Indian/Maldives'                => '+05:00, Maldives, Maldives Time',
				'Asia/Colombo'                   => '+05:30, Colombo, Sri Lanka Time',
				'Asia/Kolkata'                   => '+05:30, Kolkata, Waktu India',
				'Asia/Kathmandu'                 => '+05:45, Kathmandu, Nepal Time',
				'Asia/Almaty'                    => '+06:00, Almaty, Almaty Time',
				'Asia/Bishkek'                   => '+06:00, Bishkek, Kyrgyzstan Time',
				'Asia/Dhaka'                     => '+06:00, Dhaka, Bangladesh Time',
				'Asia/Omsk'                      => '+06:00, Omsk, Омск',
				'Asia/Yangon'                    => '+06:30, Yangon, Myanmar (Burma) Time',
				'Asia/Bangkok'                   => '+07:00, Bangkok, เวลาไทย',
				'Asia/Barnaul'                   => '+07:00, Barnaul, Барнаул',
				'Asia/Ho_Chi_Minh'               => '+07:00, Ho Chi Minh, Giờ Việt Nam',
				'Asia/Jakarta'                   => '+07:00, Jakarta, WIB',
				'Asia/Krasnoyarsk'               => '+07:00, Krasnoyarsk, Красноярск',
				'Asia/Novosibirsk'               => '+07:00, Novosibirsk, Новосибирск',
				'Asia/Phnom_Penh'                => '+07:00, Phnom_Penh, Cambodia Time',
				'Asia/Vientiane'                 => '+07:00, Vientiane, Laos Time',
				'Asia/Brunei'                    => '+08:00, Brunei, ব্রুনেই সময়',
				'Asia/Hong_Kong'                 => '+08:00, Hong Kong, 中国香港时间',
				'Asia/Irkutsk'                   => '+08:00, Irkutsk, Иркутск',
				'Asia/Kuala_Lumpur'              => '+08:00, Kuala Lumpur',
				'Asia/Makassar'                  => '+08:00, Makassar, WITA',
				'Asia/Manila'                    => '+08:00, Manila, Philippines Time',
				'Asia/Shanghai'                  => '+08:00, Shanghai, 中国时间',
				'Asia/Singapore'                 => '+08:00, Singapore, Sïngäpûru',
				'Asia/Taipei'                    => '+08:00, Taipei, Taiwan Time',
				'Asia/Ulaanbaatar'               => '+08:00, Ulaanbaatar, Улаанбаатар-н цаг',
				'Asia/Chita'                     => '+09:00, Chita, Чита',
				'Asia/Jayapura'                  => '+09:00, Jayapura, WIT',
				'Asia/Pyongyang'                 => '+09:00, Pyongyang, 북한 시간',
				'Asia/Seoul'                     => '+09:00, Seoul, 한국 시간',
				'Asia/Tokyo'                     => '+09:00, Tokyo, 日本時間',
				'Australia/Broken_Hill'          => '+09:30, Broken Hill, Broken Hill Time',
				'Australia/Darwin'               => '+09:30, Darwin, Darwin Time',
				'Asia/Vladivostok'               => '+10:00, Vladivostok, Владивосток',
				'Australia/Brisbane'             => '+10:00, Brisbane, Brisbane Time',
				'Australia/Hobart'               => '+10:00, Hobart, Hobart Time',
				'Australia/Melbourne'            => '+10:00, Melbourne, Melbourne Time',
				'Australia/Sydney'               => '+10:00, Sydney, Sydney Time',
				'Asia/Magadan'                   => '+11:00, Magadan, Магадан',
				'Asia/Sakhalin'                  => '+11:00, Sakhalin, о-в Сахалин',
				'Pacific/Efate'                  => '+11:00, Efate, Vanuatu Time',
				'Pacific/Norfolk'                => '+11:00, Norfolk, Norfolk Island Time',
				'Pacific/Noumea'                 => '+11:00, Noumea, New Caledonia Time',
				'Asia/Kamchatka'                 => '+12:00, Kamchatka, Петропавловск-Камчатский',
				'Pacific/Fiji'                   => '+12:00, Fiji, Fiji Time',
				'Pacific/Funafuti'               => '+12:00, Funafuti, Tuvalu Time',
				'Pacific/Kwajalein'              => '+12:00, Kwajalein, Kwajalein Time',
				'Pacific/Majuro'                 => '+12:00, Majuro, Marshall Islands Time',
				'Pacific/Nauru'                  => '+12:00, Nauru, Nauru Time',
				'Pacific/Tarawa'                 => '+12:00, Tarawa, Tarawa',
				'Pacific/Wake'                   => '+12:00, Wake, Wake Time',
				'Pacific/Wallis'                 => '+12:00, Wallis, Wallis & Futuna Time',
			]
		);

		Registry::set(
			'languages',
			[
				'af'     => 'Afrikaans — Afrikaans',
				'sq'     => 'Albanian — Shqip',
				'arq'    => 'Algerian Arabic — الدارجة الجزايرية',
				'am'     => 'Amharic — አማርኛ',
				'ar'     => 'Arabic — العربية',
				'hy'     => 'Armenian — Հայերեն',
				'as'     => 'Assamese — অসমীয়া',
				'ast'    => 'Asturian — Asturianu',
				'az'     => 'Azerbaijani — Azərbaycan dili',
				'bcc'    => 'Balochi Southern — بلوچی مکرانی',
				'ba'     => 'Bashkir — башҡорт теле',
				'eu'     => 'Basque — Euskara',
				'bel'    => 'Belarusian — Беларуская мова',
				'bn_BD'  => 'Bengali — বাংলা',
				'bn_IN'  => 'Bengali (India) — বাংলা (ভারত)',
				'bho'    => 'Bhojpuri — भोजपुर',
				'brx'    => 'Bodo — बोडो',
				'bs_BA'  => 'Bosnian — Bosanski',
				'bre'    => 'Breton — Brezhoneg',
				'bg_BG'  => 'Bulgarian — Български',
				'ca'     => 'Catalan — Català',
				'ceb'    => 'Cebuano — Cebuano',
				'zh_CN'  => 'Chinese (China) — 简体中文',
				'zh_HK'  => 'Chinese (Hong Kong) — 香港中文版',
				'zh_SG'  => 'Chinese (Singapore) — 中文',
				'zh_TW'  => 'Chinese (Taiwan) — 繁體中文',
				'cor'    => 'Cornish — Kernewek',
				'co'     => 'Corsican — Corsu',
				'hr'     => 'Croatian — Hrvatski',
				'cs_CZ'  => 'Czech — Čeština',
				'da_DK'  => 'Danish — Dansk',
				'dv'     => 'Dhivehi — ދިވެހި',
				'nl_NL'  => 'Dutch — Nederlands',
				'nl_BE'  => 'Dutch (Belgium) — Nederlands (België)',
				'dzo'    => 'Dzongkha — རྫོང་ཁ',
				'en_AU'  => 'English (Australia)',
				'en_CA'  => 'English (Canada)',
				'en_NZ'  => 'English (New Zealand)',
				'en_SA'  => 'English (South Africa)',
				'en_GB'  => 'English (UK)',
				'en_US'  => 'English (United States)',
				'eo'     => 'Esperanto — Esperanto',
				'et'     => 'Estonian — Eesti',
				'ewe'    => 'Ewe — Eʋegbe',
				'fo'     => 'Faroese — Føroyskt',
				'fi'     => 'Finnish — Suomi',
				'fon'    => 'Fon — fɔ̀ngbè',
				'fr_BE'  => 'French (Belgium) — Français de Belgique',
				'fr_CA'  => 'French (Canada) — Français du Canada',
				'fr_FR'  => 'French (France) — Français',
				'fy'     => 'Frisian — Frysk',
				'fuc'    => 'Fulah — Pulaar',
				'gl_ES'  => 'Galician — Galego',
				'ka_GE'  => 'Georgian — ქართული',
				'de_DE'  => 'German — Deutsch',
				'de_AT'  => 'German (Austria) — Deutsch (Österreich)',
				'de_CH'  => 'German (Switzerland) — Deutsch (Schweiz)',
				'el'     => 'Greek — Ελληνικά',
				'kal'    => 'Greenlandic — Kalaallisut',
				'gu'     => 'Gujarati — ગુજરાતી',
				'hat'    => 'Haitian Creole — Kreyol ayisyen',
				'hau'    => 'Hausa — Harshen Hausa',
				'haw_US' => 'Hawaiian — Ōlelo Hawaiʻi',
				'haz'    => 'Hazaragi — هزاره گی',
				'he_IL'  => 'Hebrew — עִבְרִית',
				'hi_IN'  => 'Hindi — हिन्दी',
				'hu_HU'  => 'Hungarian — Magyar',
				'is_IS'  => 'Icelandic — Íslenska',
				'id_ID'  => 'Indonesian — Bahasa Indonesia',
				'ga'     => 'Irish — Gaelige',
				'it_IT'  => 'Italian — Italiano',
				'ja'     => 'Japanese — 日本語',
				'kab'    => 'Kabyle — Taqbaylit',
				'kn'     => 'Kannada — ಕನ್ನಡ',
				'kk'     => 'Kazakh — Қазақ тілі',
				'km'     => 'Khmer — ភាសាខ្មែរ',
				'kin'    => 'Kinyarwanda — Ikinyarwanda',
				'ko_KR'  => 'Korean — 한국어',
				'kmr'    => 'Kurdish (Kurmanji) — Kurdî',
				'ckb'    => 'Kurdish (Sorani) — كوردی',
				'kir'    => 'Kyrgyz — Кыргызча',
				'lo'     => 'Lao — ພາສາລາວ',
				'lv'     => 'Latvian — Latviešu valoda',
				'li'     => 'Limburgish — Limburgs',
				'lin'    => 'Lingala — Ngala',
				'lt_LT'  => 'Lithuanian — Lietuvių kalba',
				'dsb'    => 'Lower Sorbian — Dolnoserbšćina',
				'lug'    => 'Luganda — Oluganda',
				'lb_LU'  => 'Luxembourgish — Lëtzebuergesch',
				'mk_MK'  => 'Macedonian — Македонски јазик',
				'mai'    => 'Maithili — मैथिली',
				'mg_MG'  => 'Malagasy — Malagasy',
				'ms_MY'  => 'Malay — Bahasa Melayu',
				'ml_IN'  => 'Malayalam — മലയാളം',
				'mlt'    => 'Maltese — Malti',
				'mri'    => 'Maori — Te Reo Māori',
				'mr'     => 'Marathi — मराठी',
				'mfe'    => 'Mauritian Creole — Kreol Morisien',
				'mn'     => 'Mongolian — Монгол',
				'me_ME'  => 'Montenegrin — Crnogorski jezik',
				'ary'    => 'Moroccan Arabic — العربية المغربية',
				'my_MM'  => 'Myanmar (Burmese) — ဗမာစာ',
				'ne_NP'  => 'Nepali — नेपाली',
				'pcm'    => 'Nigerian Pidgin — Nigerian Pidgin',
				'nb_NO'  => 'Norwegian (Bokmål) — Norsk bokmål',
				'nn_NO'  => 'Norwegian (Nynorsk) — Norsk nynorsk',
				'nqo'    => 'N’ko — ߒߞߏ',
				'oci'    => 'Occitan — Occitan',
				'ory'    => 'Oriya — ଓଡ଼ିଆ',
				'os'     => 'Ossetic — Ирон',
				'pa_IN'  => 'Panjabi (India) — ਪੰਜਾਬੀ',
				'pap_AW' => 'Papiamento (Aruba) — Papiamento',
				'pap_CW' => 'Papiamento (Curaçao and Bonaire) — Papiamentu',
				'ps'     => 'Pashto — پښتو',
				'fa_IR'  => 'Persian — فارسی',
				'fa_AF'  => 'Persian (Afghanistan) — (فارسی (افغانستان',
				'pl_PL'  => 'Polish — Polski',
				'pt_AO'  => 'Portuguese (Angola) — Português de Angola',
				'pt_BR'  => 'Portuguese (Brazil) — Português do Brasil',
				'pt_PT'  => 'Portuguese (Portugal) — Português',
				'rhg'    => 'Rohingya — Ruáinga',
				'ro_RO'  => 'Romanian — Română',
				'roh'    => 'Romansh — Rumantsch',
				'ru_RU'  => 'Russian — Русский',
				'sah'    => 'Sakha — Сахалыы',
				'sa_IN'  => 'Sanskrit — भारतम्',
				'skr'    => 'Saraiki — سرائیکی',
				'srd'    => 'Sardinian — Sardu',
				'gd'     => 'Scottish Gaelic — Gàidhlig',
				'sr_RS'  => 'Serbian — Српски језик',
				'sna'    => 'Shona — ChiShona',
				'sq_XK'  => 'Shqip (Kosovo) — Për Kosovën Shqip',
				'scn'    => 'Sicilian — Sicilianu',
				'szl'    => 'Silesian — Ślōnskŏ gŏdka',
				'snd'    => 'Sindhi — سنڌي',
				'si_LK'  => 'Sinhala — සිංහල',
				'sk_SK'  => 'Slovak — Slovenčina',
				'sl_SI'  => 'Slovenian — Slovenščina',
				'so_SO'  => 'Somali — Afsoomaali',
				'es_AR'  => 'Spanish (Argentina) — Español de Argentina',
				'es_CL'  => 'Spanish (Chile) — Español de Chile',
				'es_CO'  => 'Spanish (Colombia) — Español de Colombia',
				'es_CR'  => 'Spanish (Costa Rica) — Español de Costa Rico',
				'es_DO'  => 'Spanish (Dominican Republic) — Español de República Dominicana',
				'es_EC'  => 'Spanish (Ecuador) — Español de Ecuador',
				'es_GT'  => 'Spanish (Guatemala) — Español de Guatemala',
				'es_HN'  => 'Spanish (Honduras) — Español de Honduras',
				'es_MX'  => 'Spanish (Mexico) — Español de México',
				'es_PE'  => 'Spanish (Peru) — Español de Perú',
				'es_PR'  => 'Spanish (Puerto Rico) — Español de Puerto Rico',
				'es_ES'  => 'Spanish (Spain) — Español',
				'es_UY'  => 'Spanish (Uruguay) — Español de Uruguay',
				'es_VE'  => 'Spanish (Venezuela) — Español de Venezuela',
				'su_ID'  => 'Sundanese — Basa Sunda',
				'sw'     => 'Swahili — Kiswahili',
				'ssw'    => 'Swati — SiSwati',
				'sv_SE'  => 'Swedish — Svenska',
				'syr'    => 'Syriac — Syriac',
				'tl'     => 'Tagalog — Tagalog',
				'tah'    => 'Tahitian — Reo Tahiti',
				'tg'     => 'Tajik — Тоҷикӣ',
				'zgh'    => 'Tamazight — ⵜⴰⵎⴰⵣⵉⵖⵜ',
				'tzm'    => 'Tamazight (Central Atlas) — ⵜⴰⵎⴰⵣⵉⵖⵜ',
				'ta_IN'  => 'Tamil — தமிழ்',
				'ta_LK'  => 'Tamil (Sri Lanka) — தமிழ்',
				'tt_RU'  => 'Tatar — Татар теле',
				'te'     => 'Telugu — తెలుగు',
				'th'     => 'Thai — ไทย',
				'bo'     => 'Tibetan — བོད་སྐད',
				'tir'    => 'Tigrinya — ትግርኛ',
				'tr_TR'  => 'Turkish — Türkçe',
				'tuk'    => 'Turkmen — Türkmençe',
				'ug_CN'  => 'Uighur — Uyƣurqə',
				'uk'     => 'Ukrainian — Українська',
				'hsb'    => 'Upper Sorbian — Hornjoserbšćina',
				'ur'     => 'Urdu — اردو',
				'uz_UZ'  => 'Uzbek — O‘zbekcha',
				'vec'    => 'Venetian — Vèneto',
				'vi'     => 'Vietnamese — Tiếng Việt',
				'cy'     => 'Welsh — Cymraeg',
				'wol'    => 'Wolof — Wolof',
				'xho'    => 'Xhosa — isiXhosa',
				'yor'    => 'Yoruba — Yorùbá',
				'zul'    => 'Zulu — isiZul',
			]
		);

		Registry::set(
			'countries',
			[
				[
					'name'     => 'Afghanistan — افغانستان',
					'iso2'     => 'AF',
					'iso3'     => 'AFG',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'AFN',
						'name'   => 'Afghan afghani',
						'symbol' => '؋',
					],
				],
				[
					'name'     => 'Aland Islands — Åland',
					'iso2'     => 'AX',
					'iso3'     => 'ALA',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Albania — Shqipëria',
					'iso2'     => 'AL',
					'iso3'     => 'ALB',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'ALL',
						'name'   => 'Albanian lek',
						'symbol' => 'Lek',
					],
				],
				[
					'name'     => 'Algeria — الجزائر',
					'iso2'     => 'DZ',
					'iso3'     => 'DZA',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'DZD',
						'name'   => 'Algerian dinar',
						'symbol' => 'دج',
					],
				],
				[
					'name'     => 'American Samoa — American Samoa',
					'iso2'     => 'AS',
					'iso3'     => 'ASM',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'USD',
						'name'   => 'US Dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Andorra — Andorra',
					'iso2'     => 'AD',
					'iso3'     => 'AND',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Angola — Angola',
					'iso2'     => 'AO',
					'iso3'     => 'AGO',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'AOA',
						'name'   => 'Angolan kwanza',
						'symbol' => 'Kz',
					],
				],
				[
					'name'     => 'Anguilla — Anguilla',
					'iso2'     => 'AI',
					'iso3'     => 'AIA',
					'region'   => '',
					'currency' => [
						'code'   => 'XCD',
						'name'   => 'East Caribbean dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Antarctica — Antarctica',
					'iso2'     => 'AQ',
					'iso3'     => 'ATA',
					'region'   => '',
					'currency' => [
						'code'   => 'AAD',
						'name'   => 'Antarctican dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Antigua And Barbuda — Antigua and Barbuda',
					'iso2'     => 'AG',
					'iso3'     => 'ATG',
					'region'   => '',
					'currency' => [
						'code'   => 'XCD',
						'name'   => 'Eastern Caribbean dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Argentina — Argentina',
					'iso2'     => 'AR',
					'iso3'     => 'ARG',
					'region'   => 'SA',
					'currency' => [
						'code'   => 'ARS',
						'name'   => 'Argentine peso',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Armenia — Հայաստան',
					'iso2'     => 'AM',
					'iso3'     => 'ARM',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'AMD',
						'name'   => 'Armenian dram',
						'symbol' => '֏',
					],
				],
				[
					'name'     => 'Aruba — Aruba',
					'iso2'     => 'AW',
					'iso3'     => 'ABW',
					'region'   => '',
					'currency' => [
						'code'   => 'AWG',
						'name'   => 'Aruban florin',
						'symbol' => 'ƒ',
					],
				],
				[
					'name'     => 'Australia — Australia',
					'iso2'     => 'AU',
					'iso3'     => 'AUS',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'AUD',
						'name'   => 'Australian dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Austria — Österreich',
					'iso2'     => 'AT',
					'iso3'     => 'AUT',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Azerbaijan — Azərbaycan',
					'iso2'     => 'AZ',
					'iso3'     => 'AZE',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'AZN',
						'name'   => 'Azerbaijani manat',
						'symbol' => 'm',
					],
				],
				[
					'name'     => 'Bahrain — ‏البحرين',
					'iso2'     => 'BH',
					'iso3'     => 'BHR',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'BHD',
						'name'   => 'Bahraini dinar',
						'symbol' => '.د.ب',
					],
				],
				[
					'name'     => 'Bangladesh — Bangladesh',
					'iso2'     => 'BD',
					'iso3'     => 'BGD',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'BDT',
						'name'   => 'Bangladeshi taka',
						'symbol' => '৳',
					],
				],
				[
					'name'     => 'Barbados — Barbados',
					'iso2'     => 'BB',
					'iso3'     => 'BRB',
					'region'   => '',
					'currency' => [
						'code'   => 'BBD',
						'name'   => 'Barbadian dollar',
						'symbol' => 'Bds$',
					],
				],
				[
					'name'     => 'Belarus — Белару́сь',
					'iso2'     => 'BY',
					'iso3'     => 'BLR',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'BYN',
						'name'   => 'Belarusian ruble',
						'symbol' => 'Br',
					],
				],
				[
					'name'     => 'Belgium — België',
					'iso2'     => 'BE',
					'iso3'     => 'BEL',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Belize — Belize',
					'iso2'     => 'BZ',
					'iso3'     => 'BLZ',
					'region'   => '',
					'currency' => [
						'code'   => 'BZD',
						'name'   => 'Belize dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Benin — Bénin',
					'iso2'     => 'BJ',
					'iso3'     => 'BEN',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'XOF',
						'name'   => 'West African CFA franc',
						'symbol' => 'CFA',
					],
				],
				[
					'name'     => 'Bermuda — Bermuda',
					'iso2'     => 'BM',
					'iso3'     => 'BMU',
					'region'   => '',
					'currency' => [
						'code'   => 'BMD',
						'name'   => 'Bermudian dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Bhutan — ʼbrug-yul',
					'iso2'     => 'BT',
					'iso3'     => 'BTN',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'BTN',
						'name'   => 'Bhutanese ngultrum',
						'symbol' => 'Nu.',
					],
				],
				[
					'name'     => 'Bolivia — Bolivia',
					'iso2'     => 'BO',
					'iso3'     => 'BOL',
					'region'   => 'SA',
					'currency' => [
						'code'   => 'BOB',
						'name'   => 'Bolivian boliviano',
						'symbol' => 'Bs.',
					],
				],
				[
					'name'     => 'Bonaire, Sint Eustatius and Saba — Caribisch Nederland',
					'iso2'     => 'BQ',
					'iso3'     => 'BES',
					'region'   => '',
					'currency' => [
						'code'   => 'USD',
						'name'   => 'United States dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Bosnia and Herzegovina — Bosna i Hercegovina',
					'iso2'     => 'BA',
					'iso3'     => 'BIH',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'BAM',
						'name'   => 'Bosnia and Herzegovina convertible mark',
						'symbol' => 'KM',
					],
				],
				[
					'name'     => 'Botswana — Botswana',
					'iso2'     => 'BW',
					'iso3'     => 'BWA',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'BWP',
						'name'   => 'Botswana pula',
						'symbol' => 'P',
					],
				],
				[
					'name'     => 'Bouvet Island — Bouvetøya',
					'iso2'     => 'BV',
					'iso3'     => 'BVT',
					'region'   => '',
					'currency' => [
						'code'   => 'NOK',
						'name'   => 'Norwegian Krone',
						'symbol' => 'kr',
					],
				],
				[
					'name'     => 'Brazil — Brasil',
					'iso2'     => 'BR',
					'iso3'     => 'BRA',
					'region'   => 'SA',
					'currency' => [
						'code'   => 'BRL',
						'name'   => 'Brazilian real',
						'symbol' => 'R$',
					],
				],
				[
					'name'     => 'British Indian Ocean Territory — British Indian Ocean Territory',
					'iso2'     => 'IO',
					'iso3'     => 'IOT',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'USD',
						'name'   => 'United States dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Brunei — Negara Brunei Darussalam',
					'iso2'     => 'BN',
					'iso3'     => 'BRN',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'BND',
						'name'   => 'Brunei dollar',
						'symbol' => 'B$',
					],
				],
				[
					'name'     => 'Bulgaria — България',
					'iso2'     => 'BG',
					'iso3'     => 'BGR',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'BGN',
						'name'   => 'Bulgarian lev',
						'symbol' => 'Лв.',
					],
				],
				[
					'name'     => 'Burkina Faso — Burkina Faso',
					'iso2'     => 'BF',
					'iso3'     => 'BFA',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'XOF',
						'name'   => 'West African CFA franc',
						'symbol' => 'CFA',
					],
				],
				[
					'name'     => 'Burundi — Burundi',
					'iso2'     => 'BI',
					'iso3'     => 'BDI',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'BIF',
						'name'   => 'Burundian franc',
						'symbol' => 'FBu',
					],
				],
				[
					'name'     => 'Cambodia — Kâmpŭchéa',
					'iso2'     => 'KH',
					'iso3'     => 'KHM',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'KHR',
						'name'   => 'Cambodian riel',
						'symbol' => 'KHR',
					],
				],
				[
					'name'     => 'Cameroon — Cameroon',
					'iso2'     => 'CM',
					'iso3'     => 'CMR',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'XAF',
						'name'   => 'Central African CFA franc',
						'symbol' => 'FCFA',
					],
				],
				[
					'name'     => 'Canada — Canada',
					'iso2'     => 'CA',
					'iso3'     => 'CAN',
					'region'   => '',
					'currency' => [
						'code'   => 'CAD',
						'name'   => 'Canadian dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Cape Verde — Cabo Verde',
					'iso2'     => 'CV',
					'iso3'     => 'CPV',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'CVE',
						'name'   => 'Cape Verdean escudo',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Cayman Islands — Cayman Islands',
					'iso2'     => 'KY',
					'iso3'     => 'CYM',
					'region'   => '',
					'currency' => [
						'code'   => 'KYD',
						'name'   => 'Cayman Islands dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Central African Republic — Ködörösêse tî Bêafrîka',
					'iso2'     => 'CF',
					'iso3'     => 'CAF',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'XAF',
						'name'   => 'Central African CFA franc',
						'symbol' => 'FCFA',
					],
				],
				[
					'name'     => 'Chad — Tchad',
					'iso2'     => 'TD',
					'iso3'     => 'TCD',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'XAF',
						'name'   => 'Central African CFA franc',
						'symbol' => 'FCFA',
					],
				],
				[
					'name'     => 'Chile — Chile',
					'iso2'     => 'CL',
					'iso3'     => 'CHL',
					'region'   => 'SA',
					'currency' => [
						'code'   => 'CLP',
						'name'   => 'Chilean peso',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'China — 中国',
					'iso2'     => 'CN',
					'iso3'     => 'CHN',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'CNY',
						'name'   => 'Chinese yuan',
						'symbol' => '¥',
					],
				],
				[
					'name'     => 'Christmas Island — Christmas Island',
					'iso2'     => 'CX',
					'iso3'     => 'CXR',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'AUD',
						'name'   => 'Australian dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Cocos (Keeling) Islands — Cocos (Keeling) Islands',
					'iso2'     => 'CC',
					'iso3'     => 'CCK',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'AUD',
						'name'   => 'Australian dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Colombia — Colombia',
					'iso2'     => 'CO',
					'iso3'     => 'COL',
					'region'   => 'SA',
					'currency' => [
						'code'   => 'COP',
						'name'   => 'Colombian peso',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Comoros — Komori',
					'iso2'     => 'KM',
					'iso3'     => 'COM',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'KMF',
						'name'   => 'Comorian franc',
						'symbol' => 'CF',
					],
				],
				[
					'name'     => 'Congo — République du Congo',
					'iso2'     => 'CG',
					'iso3'     => 'COG',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'XAF',
						'name'   => 'Central African CFA franc',
						'symbol' => 'FC',
					],
				],
				[
					'name'     => 'Cook Islands — Cook Islands',
					'iso2'     => 'CK',
					'iso3'     => 'COK',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'NZD',
						'name'   => 'Cook Islands dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Costa Rica — Costa Rica',
					'iso2'     => 'CR',
					'iso3'     => 'CRI',
					'region'   => '',
					'currency' => [
						'code'   => 'CRC',
						'name'   => 'Costa Rican colón',
						'symbol' => '₡',
					],
				],
				[
					'name'     => 'Cote D\'Ivoire (Ivory Coast) — ',
					'iso2'     => 'CI',
					'iso3'     => 'CIV',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'XOF',
						'name'   => 'West African CFA franc',
						'symbol' => 'CFA',
					],
				],
				[
					'name'     => 'Croatia — Hrvatska',
					'iso2'     => 'HR',
					'iso3'     => 'HRV',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'HRK',
						'name'   => 'Croatian kuna',
						'symbol' => 'kn',
					],
				],
				[
					'name'     => 'Cuba — Cuba',
					'iso2'     => 'CU',
					'iso3'     => 'CUB',
					'region'   => '',
					'currency' => [
						'code'   => 'CUP',
						'name'   => 'Cuban peso',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Curaçao — Curaçao',
					'iso2'     => 'CW',
					'iso3'     => 'CUW',
					'region'   => '',
					'currency' => [
						'code'   => 'ANG',
						'name'   => 'Netherlands Antillean guilder',
						'symbol' => 'ƒ',
					],
				],
				[
					'name'     => 'Cyprus — Κύπρος',
					'iso2'     => 'CY',
					'iso3'     => 'CYP',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Czech Republic — Česká republika',
					'iso2'     => 'CZ',
					'iso3'     => 'CZE',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'CZK',
						'name'   => 'Czech koruna',
						'symbol' => 'Kč',
					],
				],
				[
					'name'     => 'Democratic Republic of the Congo — République démocratique du Congo',
					'iso2'     => 'CD',
					'iso3'     => 'COD',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'CDF',
						'name'   => 'Congolese Franc',
						'symbol' => 'FC',
					],
				],
				[
					'name'     => 'Denmark — Danmark',
					'iso2'     => 'DK',
					'iso3'     => 'DNK',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'DKK',
						'name'   => 'Danish krone',
						'symbol' => 'Kr.',
					],
				],
				[
					'name'     => 'Djibouti — Djibouti',
					'iso2'     => 'DJ',
					'iso3'     => 'DJI',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'DJF',
						'name'   => 'Djiboutian franc',
						'symbol' => 'Fdj',
					],
				],
				[
					'name'     => 'Dominica — Dominica',
					'iso2'     => 'DM',
					'iso3'     => 'DMA',
					'region'   => '',
					'currency' => [
						'code'   => 'XCD',
						'name'   => 'Eastern Caribbean dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Dominican Republic — República Dominicana',
					'iso2'     => 'DO',
					'iso3'     => 'DOM',
					'region'   => '',
					'currency' => [
						'code'   => 'DOP',
						'name'   => 'Dominican peso',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'East Timor — Timor-Leste',
					'iso2'     => 'TL',
					'iso3'     => 'TLS',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'USD',
						'name'   => 'United States dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Ecuador — Ecuador',
					'iso2'     => 'EC',
					'iso3'     => 'ECU',
					'region'   => 'SA',
					'currency' => [
						'code'   => 'USD',
						'name'   => 'United States dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Egypt — مصر‎',
					'iso2'     => 'EG',
					'iso3'     => 'EGY',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'EGP',
						'name'   => 'Egyptian pound',
						'symbol' => 'ج.م',
					],
				],
				[
					'name'     => 'El Salvador — El Salvador',
					'iso2'     => 'SV',
					'iso3'     => 'SLV',
					'region'   => '',
					'currency' => [
						'code'   => 'USD',
						'name'   => 'United States dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Equatorial Guinea — Guinea Ecuatorial',
					'iso2'     => 'GQ',
					'iso3'     => 'GNQ',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'XAF',
						'name'   => 'Central African CFA franc',
						'symbol' => 'FCFA',
					],
				],
				[
					'name'     => 'Eritrea — ኤርትራ',
					'iso2'     => 'ER',
					'iso3'     => 'ERI',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'ERN',
						'name'   => 'Eritrean nakfa',
						'symbol' => 'Nfk',
					],
				],
				[
					'name'     => 'Estonia — Eesti',
					'iso2'     => 'EE',
					'iso3'     => 'EST',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Ethiopia — ኢትዮጵያ',
					'iso2'     => 'ET',
					'iso3'     => 'ETH',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'ETB',
						'name'   => 'Ethiopian birr',
						'symbol' => 'Nkf',
					],
				],
				[
					'name'     => 'Falkland Islands — Falkland Islands',
					'iso2'     => 'FK',
					'iso3'     => 'FLK',
					'region'   => 'SA',
					'currency' => [
						'code'   => 'FKP',
						'name'   => 'Falkland Islands pound',
						'symbol' => '£',
					],
				],
				[
					'name'     => 'Faroe Islands — Føroyar',
					'iso2'     => 'FO',
					'iso3'     => 'FRO',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'DKK',
						'name'   => 'Danish krone',
						'symbol' => 'Kr.',
					],
				],
				[
					'name'     => 'Fiji Islands — Fiji',
					'iso2'     => 'FJ',
					'iso3'     => 'FJI',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'FJD',
						'name'   => 'Fijian dollar',
						'symbol' => 'FJ$',
					],
				],
				[
					'name'     => 'Finland — Suomi',
					'iso2'     => 'FI',
					'iso3'     => 'FIN',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'France — France',
					'iso2'     => 'FR',
					'iso3'     => 'FRA',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'French Guiana — Guyane française',
					'iso2'     => 'GF',
					'iso3'     => 'GUF',
					'region'   => 'SA',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'French Polynesia — Polynésie française',
					'iso2'     => 'PF',
					'iso3'     => 'PYF',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'XPF',
						'name'   => 'CFP franc',
						'symbol' => '₣',
					],
				],
				[
					'name'     => 'French Southern Territories — Territoire des Terres australes et antarctiques fr',
					'iso2'     => 'TF',
					'iso3'     => 'ATF',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Gabon — Gabon',
					'iso2'     => 'GA',
					'iso3'     => 'GAB',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'XAF',
						'name'   => 'Central African CFA franc',
						'symbol' => 'FCFA',
					],
				],
				[
					'name'     => 'Gambia The — Gambia',
					'iso2'     => 'GM',
					'iso3'     => 'GMB',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'GMD',
						'name'   => 'Gambian dalasi',
						'symbol' => 'D',
					],
				],
				[
					'name'     => 'Georgia — საქართველო',
					'iso2'     => 'GE',
					'iso3'     => 'GEO',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'GEL',
						'name'   => 'Georgian lari',
						'symbol' => 'ლ',
					],
				],
				[
					'name'     => 'Germany — Deutschland',
					'iso2'     => 'DE',
					'iso3'     => 'DEU',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Ghana — Ghana',
					'iso2'     => 'GH',
					'iso3'     => 'GHA',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'GHS',
						'name'   => 'Ghanaian cedi',
						'symbol' => 'GH₵',
					],
				],
				[
					'name'     => 'Gibraltar — Gibraltar',
					'iso2'     => 'GI',
					'iso3'     => 'GIB',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'GIP',
						'name'   => 'Gibraltar pound',
						'symbol' => '£',
					],
				],
				[
					'name'     => 'Greece — Ελλάδα',
					'iso2'     => 'GR',
					'iso3'     => 'GRC',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Greenland — Kalaallit Nunaat',
					'iso2'     => 'GL',
					'iso3'     => 'GRL',
					'region'   => '',
					'currency' => [
						'code'   => 'DKK',
						'name'   => 'Danish krone',
						'symbol' => 'Kr.',
					],
				],
				[
					'name'     => 'Grenada — Grenada',
					'iso2'     => 'GD',
					'iso3'     => 'GRD',
					'region'   => '',
					'currency' => [
						'code'   => 'XCD',
						'name'   => 'Eastern Caribbean dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Guadeloupe — Guadeloupe',
					'iso2'     => 'GP',
					'iso3'     => 'GLP',
					'region'   => '',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Guam — Guam',
					'iso2'     => 'GU',
					'iso3'     => 'GUM',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'USD',
						'name'   => 'US Dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Guatemala — Guatemala',
					'iso2'     => 'GT',
					'iso3'     => 'GTM',
					'region'   => '',
					'currency' => [
						'code'   => 'GTQ',
						'name'   => 'Guatemalan quetzal',
						'symbol' => 'Q',
					],
				],
				[
					'name'     => 'Guernsey and Alderney — Guernsey',
					'iso2'     => 'GG',
					'iso3'     => 'GGY',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'GBP',
						'name'   => 'British pound',
						'symbol' => '£',
					],
				],
				[
					'name'     => 'Guinea — Guinée',
					'iso2'     => 'GN',
					'iso3'     => 'GIN',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'GNF',
						'name'   => 'Guinean franc',
						'symbol' => 'FG',
					],
				],
				[
					'name'     => 'Guinea-Bissau — Guiné-Bissau',
					'iso2'     => 'GW',
					'iso3'     => 'GNB',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'XOF',
						'name'   => 'West African CFA franc',
						'symbol' => 'CFA',
					],
				],
				[
					'name'     => 'Guyana — Guyana',
					'iso2'     => 'GY',
					'iso3'     => 'GUY',
					'region'   => 'SA',
					'currency' => [
						'code'   => 'GYD',
						'name'   => 'Guyanese dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Haiti — Haïti',
					'iso2'     => 'HT',
					'iso3'     => 'HTI',
					'region'   => '',
					'currency' => [
						'code'   => 'HTG',
						'name'   => 'Haitian gourde',
						'symbol' => 'G',
					],
				],
				[
					'name'     => 'Heard Island and McDonald Islands — Heard Island and McDonald Islands',
					'iso2'     => 'HM',
					'iso3'     => 'HMD',
					'region'   => '',
					'currency' => [
						'code'   => 'AUD',
						'name'   => 'Australian dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Honduras — Honduras',
					'iso2'     => 'HN',
					'iso3'     => 'HND',
					'region'   => '',
					'currency' => [
						'code'   => 'HNL',
						'name'   => 'Honduran lempira',
						'symbol' => 'L',
					],
				],
				[
					'name'     => 'Hong Kong S.A.R. — 香港',
					'iso2'     => 'HK',
					'iso3'     => 'HKG',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'HKD',
						'name'   => 'Hong Kong dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Hungary — Magyarország',
					'iso2'     => 'HU',
					'iso3'     => 'HUN',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'HUF',
						'name'   => 'Hungarian forint',
						'symbol' => 'Ft',
					],
				],
				[
					'name'     => 'Iceland — Ísland',
					'iso2'     => 'IS',
					'iso3'     => 'ISL',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'ISK',
						'name'   => 'Icelandic króna',
						'symbol' => 'kr',
					],
				],
				[
					'name'     => 'India — भारत',
					'iso2'     => 'IN',
					'iso3'     => 'IND',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'INR',
						'name'   => 'Indian rupee',
						'symbol' => '₹',
					],
				],
				[
					'name'     => 'Indonesia — Indonesia',
					'iso2'     => 'ID',
					'iso3'     => 'IDN',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'IDR',
						'name'   => 'Indonesian rupiah',
						'symbol' => 'Rp',
					],
				],
				[
					'name'     => 'Iran — ایران',
					'iso2'     => 'IR',
					'iso3'     => 'IRN',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'IRR',
						'name'   => 'Iranian rial',
						'symbol' => '﷼',
					],
				],
				[
					'name'     => 'Iraq — العراق',
					'iso2'     => 'IQ',
					'iso3'     => 'IRQ',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'IQD',
						'name'   => 'Iraqi dinar',
						'symbol' => 'د.ع',
					],
				],
				[
					'name'     => 'Ireland — Éire',
					'iso2'     => 'IE',
					'iso3'     => 'IRL',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Israel — יִשְׂרָאֵל',
					'iso2'     => 'IL',
					'iso3'     => 'ISR',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'ILS',
						'name'   => 'Israeli new shekel',
						'symbol' => '₪',
					],
				],
				[
					'name'     => 'Italy — Italia',
					'iso2'     => 'IT',
					'iso3'     => 'ITA',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Jamaica — Jamaica',
					'iso2'     => 'JM',
					'iso3'     => 'JAM',
					'region'   => '',
					'currency' => [
						'code'   => 'JMD',
						'name'   => 'Jamaican dollar',
						'symbol' => 'J$',
					],
				],
				[
					'name'     => 'Japan — 日本',
					'iso2'     => 'JP',
					'iso3'     => 'JPN',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'JPY',
						'name'   => 'Japanese yen',
						'symbol' => '¥',
					],
				],
				[
					'name'     => 'Jersey — Jersey',
					'iso2'     => 'JE',
					'iso3'     => 'JEY',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'GBP',
						'name'   => 'British pound',
						'symbol' => '£',
					],
				],
				[
					'name'     => 'Jordan — الأردن',
					'iso2'     => 'JO',
					'iso3'     => 'JOR',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'JOD',
						'name'   => 'Jordanian dinar',
						'symbol' => 'ا.د',
					],
				],
				[
					'name'     => 'Kazakhstan — Қазақстан',
					'iso2'     => 'KZ',
					'iso3'     => 'KAZ',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'KZT',
						'name'   => 'Kazakhstani tenge',
						'symbol' => 'лв',
					],
				],
				[
					'name'     => 'Kenya — Kenya',
					'iso2'     => 'KE',
					'iso3'     => 'KEN',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'KES',
						'name'   => 'Kenyan shilling',
						'symbol' => 'KSh',
					],
				],
				[
					'name'     => 'Kiribati — Kiribati',
					'iso2'     => 'KI',
					'iso3'     => 'KIR',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'AUD',
						'name'   => 'Australian dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Kosovo — Republika e Kosovës',
					'iso2'     => 'XK',
					'iso3'     => 'XKX',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Kuwait — الكويت',
					'iso2'     => 'KW',
					'iso3'     => 'KWT',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'KWD',
						'name'   => 'Kuwaiti dinar',
						'symbol' => 'ك.د',
					],
				],
				[
					'name'     => 'Kyrgyzstan — Кыргызстан',
					'iso2'     => 'KG',
					'iso3'     => 'KGZ',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'KGS',
						'name'   => 'Kyrgyzstani som',
						'symbol' => 'лв',
					],
				],
				[
					'name'     => 'Laos — ສປປລາວ',
					'iso2'     => 'LA',
					'iso3'     => 'LAO',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'LAK',
						'name'   => 'Lao kip',
						'symbol' => '₭',
					],
				],
				[
					'name'     => 'Latvia — Latvija',
					'iso2'     => 'LV',
					'iso3'     => 'LVA',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Lebanon — لبنان',
					'iso2'     => 'LB',
					'iso3'     => 'LBN',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'LBP',
						'name'   => 'Lebanese pound',
						'symbol' => '£',
					],
				],
				[
					'name'     => 'Lesotho — Lesotho',
					'iso2'     => 'LS',
					'iso3'     => 'LSO',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'LSL',
						'name'   => 'Lesotho loti',
						'symbol' => 'L',
					],
				],
				[
					'name'     => 'Liberia — Liberia',
					'iso2'     => 'LR',
					'iso3'     => 'LBR',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'LRD',
						'name'   => 'Liberian dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Libya — ‏ليبيا',
					'iso2'     => 'LY',
					'iso3'     => 'LBY',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'LYD',
						'name'   => 'Libyan dinar',
						'symbol' => 'د.ل',
					],
				],
				[
					'name'     => 'Liechtenstein — Liechtenstein',
					'iso2'     => 'LI',
					'iso3'     => 'LIE',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'CHF',
						'name'   => 'Swiss franc',
						'symbol' => 'CHf',
					],
				],
				[
					'name'     => 'Lithuania — Lietuva',
					'iso2'     => 'LT',
					'iso3'     => 'LTU',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Luxembourg — Luxembourg',
					'iso2'     => 'LU',
					'iso3'     => 'LUX',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Macau S.A.R. — 澳門',
					'iso2'     => 'MO',
					'iso3'     => 'MAC',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'MOP',
						'name'   => 'Macanese pataca',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Madagascar — Madagasikara',
					'iso2'     => 'MG',
					'iso3'     => 'MDG',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'MGA',
						'name'   => 'Malagasy ariary',
						'symbol' => 'Ar',
					],
				],
				[
					'name'     => 'Malawi — Malawi',
					'iso2'     => 'MW',
					'iso3'     => 'MWI',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'MWK',
						'name'   => 'Malawian kwacha',
						'symbol' => 'MK',
					],
				],
				[
					'name'     => 'Malaysia — Malaysia',
					'iso2'     => 'MY',
					'iso3'     => 'MYS',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'MYR',
						'name'   => 'Malaysian ringgit',
						'symbol' => 'RM',
					],
				],
				[
					'name'     => 'Maldives — Maldives',
					'iso2'     => 'MV',
					'iso3'     => 'MDV',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'MVR',
						'name'   => 'Maldivian rufiyaa',
						'symbol' => 'Rf',
					],
				],
				[
					'name'     => 'Mali — Mali',
					'iso2'     => 'ML',
					'iso3'     => 'MLI',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'XOF',
						'name'   => 'West African CFA franc',
						'symbol' => 'CFA',
					],
				],
				[
					'name'     => 'Malta — Malta',
					'iso2'     => 'MT',
					'iso3'     => 'MLT',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Man (Isle of) — Isle of Man',
					'iso2'     => 'IM',
					'iso3'     => 'IMN',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'GBP',
						'name'   => 'British pound',
						'symbol' => '£',
					],
				],
				[
					'name'     => 'Marshall Islands — M̧ajeļ',
					'iso2'     => 'MH',
					'iso3'     => 'MHL',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'USD',
						'name'   => 'United States dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Martinique — Martinique',
					'iso2'     => 'MQ',
					'iso3'     => 'MTQ',
					'region'   => '',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Mauritania — موريتانيا',
					'iso2'     => 'MR',
					'iso3'     => 'MRT',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'MRO',
						'name'   => 'Mauritanian ouguiya',
						'symbol' => 'MRU',
					],
				],
				[
					'name'     => 'Mauritius — Maurice',
					'iso2'     => 'MU',
					'iso3'     => 'MUS',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'MUR',
						'name'   => 'Mauritian rupee',
						'symbol' => '₨',
					],
				],
				[
					'name'     => 'Mayotte — Mayotte',
					'iso2'     => 'YT',
					'iso3'     => 'MYT',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Mexico — México',
					'iso2'     => 'MX',
					'iso3'     => 'MEX',
					'region'   => '',
					'currency' => [
						'code'   => 'MXN',
						'name'   => 'Mexican peso',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Micronesia — Micronesia',
					'iso2'     => 'FM',
					'iso3'     => 'FSM',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'USD',
						'name'   => 'United States dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Moldova — Moldova',
					'iso2'     => 'MD',
					'iso3'     => 'MDA',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'MDL',
						'name'   => 'Moldovan leu',
						'symbol' => 'L',
					],
				],
				[
					'name'     => 'Monaco — Monaco',
					'iso2'     => 'MC',
					'iso3'     => 'MCO',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Mongolia — Монгол улс',
					'iso2'     => 'MN',
					'iso3'     => 'MNG',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'MNT',
						'name'   => 'Mongolian tögrög',
						'symbol' => '₮',
					],
				],
				[
					'name'     => 'Montenegro — Црна Гора',
					'iso2'     => 'ME',
					'iso3'     => 'MNE',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Montserrat — Montserrat',
					'iso2'     => 'MS',
					'iso3'     => 'MSR',
					'region'   => '',
					'currency' => [
						'code'   => 'XCD',
						'name'   => 'Eastern Caribbean dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Morocco — المغرب',
					'iso2'     => 'MA',
					'iso3'     => 'MAR',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'MAD',
						'name'   => 'Moroccan dirham',
						'symbol' => 'DH',
					],
				],
				[
					'name'     => 'Mozambique — Moçambique',
					'iso2'     => 'MZ',
					'iso3'     => 'MOZ',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'MZN',
						'name'   => 'Mozambican metical',
						'symbol' => 'MT',
					],
				],
				[
					'name'     => 'Myanmar — မြန်မာ',
					'iso2'     => 'MM',
					'iso3'     => 'MMR',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'MMK',
						'name'   => 'Burmese kyat',
						'symbol' => 'K',
					],
				],
				[
					'name'     => 'Namibia — Namibia',
					'iso2'     => 'NA',
					'iso3'     => 'NAM',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'NAD',
						'name'   => 'Namibian dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Nauru — Nauru',
					'iso2'     => 'NR',
					'iso3'     => 'NRU',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'AUD',
						'name'   => 'Australian dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Nepal — नपल',
					'iso2'     => 'NP',
					'iso3'     => 'NPL',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'NPR',
						'name'   => 'Nepalese rupee',
						'symbol' => '₨',
					],
				],
				[
					'name'     => 'Netherlands — Nederland',
					'iso2'     => 'NL',
					'iso3'     => 'NLD',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'New Caledonia — Nouvelle-Calédonie',
					'iso2'     => 'NC',
					'iso3'     => 'NCL',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'XPF',
						'name'   => 'CFP franc',
						'symbol' => '₣',
					],
				],
				[
					'name'     => 'New Zealand — New Zealand',
					'iso2'     => 'NZ',
					'iso3'     => 'NZL',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'NZD',
						'name'   => 'New Zealand dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Nicaragua — Nicaragua',
					'iso2'     => 'NI',
					'iso3'     => 'NIC',
					'region'   => '',
					'currency' => [
						'code'   => 'NIO',
						'name'   => 'Nicaraguan córdoba',
						'symbol' => 'C$',
					],
				],
				[
					'name'     => 'Niger — Niger',
					'iso2'     => 'NE',
					'iso3'     => 'NER',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'XOF',
						'name'   => 'West African CFA franc',
						'symbol' => 'CFA',
					],
				],
				[
					'name'     => 'Nigeria — Nigeria',
					'iso2'     => 'NG',
					'iso3'     => 'NGA',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'NGN',
						'name'   => 'Nigerian naira',
						'symbol' => '₦',
					],
				],
				[
					'name'     => 'Niue — Niuē',
					'iso2'     => 'NU',
					'iso3'     => 'NIU',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'NZD',
						'name'   => 'New Zealand dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Norfolk Island — Norfolk Island',
					'iso2'     => 'NF',
					'iso3'     => 'NFK',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'AUD',
						'name'   => 'Australian dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'North Korea — 북한',
					'iso2'     => 'KP',
					'iso3'     => 'PRK',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'KPW',
						'name'   => 'North Korean Won',
						'symbol' => '₩',
					],
				],
				[
					'name'     => 'North Macedonia — Северна Македонија',
					'iso2'     => 'MK',
					'iso3'     => 'MKD',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'MKD',
						'name'   => 'Denar',
						'symbol' => 'ден',
					],
				],
				[
					'name'     => 'Northern Mariana Islands — Northern Mariana Islands',
					'iso2'     => 'MP',
					'iso3'     => 'MNP',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'USD',
						'name'   => 'United States dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Norway — Norge',
					'iso2'     => 'NO',
					'iso3'     => 'NOR',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'NOK',
						'name'   => 'Norwegian krone',
						'symbol' => 'kr',
					],
				],
				[
					'name'     => 'Oman — عمان',
					'iso2'     => 'OM',
					'iso3'     => 'OMN',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'OMR',
						'name'   => 'Omani rial',
						'symbol' => '.ع.ر',
					],
				],
				[
					'name'     => 'Pakistan — Pakistan',
					'iso2'     => 'PK',
					'iso3'     => 'PAK',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'PKR',
						'name'   => 'Pakistani rupee',
						'symbol' => '₨',
					],
				],
				[
					'name'     => 'Palau — Palau',
					'iso2'     => 'PW',
					'iso3'     => 'PLW',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'USD',
						'name'   => 'United States dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Palestinian Territory Occupied — فلسطين',
					'iso2'     => 'PS',
					'iso3'     => 'PSE',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'ILS',
						'name'   => 'Israeli new shekel',
						'symbol' => '₪',
					],
				],
				[
					'name'     => 'Panama — Panamá',
					'iso2'     => 'PA',
					'iso3'     => 'PAN',
					'region'   => '',
					'currency' => [
						'code'   => 'PAB',
						'name'   => 'Panamanian balboa',
						'symbol' => 'B/.',
					],
				],
				[
					'name'     => 'Papua new Guinea — Papua Niugini',
					'iso2'     => 'PG',
					'iso3'     => 'PNG',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'PGK',
						'name'   => 'Papua New Guinean kina',
						'symbol' => 'K',
					],
				],
				[
					'name'     => 'Paraguay — Paraguay',
					'iso2'     => 'PY',
					'iso3'     => 'PRY',
					'region'   => 'SA',
					'currency' => [
						'code'   => 'PYG',
						'name'   => 'Paraguayan guarani',
						'symbol' => '₲',
					],
				],
				[
					'name'     => 'Peru — Perú',
					'iso2'     => 'PE',
					'iso3'     => 'PER',
					'region'   => 'SA',
					'currency' => [
						'code'   => 'PEN',
						'name'   => 'Peruvian sol',
						'symbol' => 'S/.',
					],
				],
				[
					'name'     => 'Philippines — Pilipinas',
					'iso2'     => 'PH',
					'iso3'     => 'PHL',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'PHP',
						'name'   => 'Philippine peso',
						'symbol' => '₱',
					],
				],
				[
					'name'     => 'Pitcairn Island — Pitcairn Islands',
					'iso2'     => 'PN',
					'iso3'     => 'PCN',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'NZD',
						'name'   => 'New Zealand dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Poland — Polska',
					'iso2'     => 'PL',
					'iso3'     => 'POL',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'PLN',
						'name'   => 'Polish złoty',
						'symbol' => 'zł',
					],
				],
				[
					'name'     => 'Portugal — Portugal',
					'iso2'     => 'PT',
					'iso3'     => 'PRT',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Puerto Rico — Puerto Rico',
					'iso2'     => 'PR',
					'iso3'     => 'PRI',
					'region'   => '',
					'currency' => [
						'code'   => 'USD',
						'name'   => 'United States dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Qatar — قطر',
					'iso2'     => 'QA',
					'iso3'     => 'QAT',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'QAR',
						'name'   => 'Qatari riyal',
						'symbol' => 'ق.ر',
					],
				],
				[
					'name'     => 'Reunion — La Réunion',
					'iso2'     => 'RE',
					'iso3'     => 'REU',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Romania — România',
					'iso2'     => 'RO',
					'iso3'     => 'ROU',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'RON',
						'name'   => 'Romanian leu',
						'symbol' => 'lei',
					],
				],
				[
					'name'     => 'Russia — Россия',
					'iso2'     => 'RU',
					'iso3'     => 'RUS',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'RUB',
						'name'   => 'Russian ruble',
						'symbol' => '₽',
					],
				],
				[
					'name'     => 'Rwanda — Rwanda',
					'iso2'     => 'RW',
					'iso3'     => 'RWA',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'RWF',
						'name'   => 'Rwandan franc',
						'symbol' => 'FRw',
					],
				],
				[
					'name'     => 'Saint Helena — Saint Helena',
					'iso2'     => 'SH',
					'iso3'     => 'SHN',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'SHP',
						'name'   => 'Saint Helena pound',
						'symbol' => '£',
					],
				],
				[
					'name'     => 'Saint Kitts And Nevis — Saint Kitts and Nevis',
					'iso2'     => 'KN',
					'iso3'     => 'KNA',
					'region'   => '',
					'currency' => [
						'code'   => 'XCD',
						'name'   => 'Eastern Caribbean dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Saint Lucia — Saint Lucia',
					'iso2'     => 'LC',
					'iso3'     => 'LCA',
					'region'   => '',
					'currency' => [
						'code'   => 'XCD',
						'name'   => 'Eastern Caribbean dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Saint Pierre and Miquelon — Saint-Pierre-et-Miquelon',
					'iso2'     => 'PM',
					'iso3'     => 'SPM',
					'region'   => '',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Saint Vincent And The Grenadines — Saint Vincent and the Grenadines',
					'iso2'     => 'VC',
					'iso3'     => 'VCT',
					'region'   => '',
					'currency' => [
						'code'   => 'XCD',
						'name'   => 'Eastern Caribbean dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Saint-Barthelemy — Saint-Barthélemy',
					'iso2'     => 'BL',
					'iso3'     => 'BLM',
					'region'   => '',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Saint-Martin (French part) — Saint-Martin',
					'iso2'     => 'MF',
					'iso3'     => 'MAF',
					'region'   => '',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Samoa — Samoa',
					'iso2'     => 'WS',
					'iso3'     => 'WSM',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'WST',
						'name'   => 'Samoan tālā',
						'symbol' => 'SAT',
					],
				],
				[
					'name'     => 'San Marino — San Marino',
					'iso2'     => 'SM',
					'iso3'     => 'SMR',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Sao Tome and Principe — São Tomé e Príncipe',
					'iso2'     => 'ST',
					'iso3'     => 'STP',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'STD',
						'name'   => 'Dobra',
						'symbol' => 'Db',
					],
				],
				[
					'name'     => 'Saudi Arabia — المملكة العربية السعودية',
					'iso2'     => 'SA',
					'iso3'     => 'SAU',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'SAR',
						'name'   => 'Saudi riyal',
						'symbol' => '﷼',
					],
				],
				[
					'name'     => 'Senegal — Sénégal',
					'iso2'     => 'SN',
					'iso3'     => 'SEN',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'XOF',
						'name'   => 'West African CFA franc',
						'symbol' => 'CFA',
					],
				],
				[
					'name'     => 'Serbia — Србија',
					'iso2'     => 'RS',
					'iso3'     => 'SRB',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'RSD',
						'name'   => 'Serbian dinar',
						'symbol' => 'din',
					],
				],
				[
					'name'     => 'Seychelles — Seychelles',
					'iso2'     => 'SC',
					'iso3'     => 'SYC',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'SCR',
						'name'   => 'Seychellois rupee',
						'symbol' => 'SRe',
					],
				],
				[
					'name'     => 'Sierra Leone — Sierra Leone',
					'iso2'     => 'SL',
					'iso3'     => 'SLE',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'SLL',
						'name'   => 'Sierra Leonean leone',
						'symbol' => 'Le',
					],
				],
				[
					'name'     => 'Singapore — Singapore',
					'iso2'     => 'SG',
					'iso3'     => 'SGP',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'SGD',
						'name'   => 'Singapore dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Sint Maarten (Dutch part) — Sint Maarten',
					'iso2'     => 'SX',
					'iso3'     => 'SXM',
					'region'   => '',
					'currency' => [
						'code'   => 'ANG',
						'name'   => 'Netherlands Antillean guilder',
						'symbol' => 'ƒ',
					],
				],
				[
					'name'     => 'Slovakia — Slovensko',
					'iso2'     => 'SK',
					'iso3'     => 'SVK',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Slovenia — Slovenija',
					'iso2'     => 'SI',
					'iso3'     => 'SVN',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Solomon Islands — Solomon Islands',
					'iso2'     => 'SB',
					'iso3'     => 'SLB',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'SBD',
						'name'   => 'Solomon Islands dollar',
						'symbol' => 'Si$',
					],
				],
				[
					'name'     => 'Somalia — Soomaaliya',
					'iso2'     => 'SO',
					'iso3'     => 'SOM',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'SOS',
						'name'   => 'Somali shilling',
						'symbol' => 'Sh.so.',
					],
				],
				[
					'name'     => 'South Africa — South Africa',
					'iso2'     => 'ZA',
					'iso3'     => 'ZAF',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'ZAR',
						'name'   => 'South African rand',
						'symbol' => 'R',
					],
				],
				[
					'name'     => 'South Georgia — South Georgia',
					'iso2'     => 'GS',
					'iso3'     => 'SGS',
					'region'   => 'SA',
					'currency' => [
						'code'   => 'GBP',
						'name'   => 'British pound',
						'symbol' => '£',
					],
				],
				[
					'name'     => 'South Korea — 대한민국',
					'iso2'     => 'KR',
					'iso3'     => 'KOR',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'KRW',
						'name'   => 'Won',
						'symbol' => '₩',
					],
				],
				[
					'name'     => 'South Sudan — South Sudan',
					'iso2'     => 'SS',
					'iso3'     => 'SSD',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'SSP',
						'name'   => 'South Sudanese pound',
						'symbol' => '£',
					],
				],
				[
					'name'     => 'Spain — España',
					'iso2'     => 'ES',
					'iso3'     => 'ESP',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Sri Lanka — śrī laṃkāva',
					'iso2'     => 'LK',
					'iso3'     => 'LKA',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'LKR',
						'name'   => 'Sri Lankan rupee',
						'symbol' => 'Rs',
					],
				],
				[
					'name'     => 'Sudan — السودان',
					'iso2'     => 'SD',
					'iso3'     => 'SDN',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'SDG',
						'name'   => 'Sudanese pound',
						'symbol' => '.س.ج',
					],
				],
				[
					'name'     => 'Suriname — Suriname',
					'iso2'     => 'SR',
					'iso3'     => 'SUR',
					'region'   => 'SA',
					'currency' => [
						'code'   => 'SRD',
						'name'   => 'Surinamese dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Svalbard And Jan Mayen Islands — Svalbard og Jan Mayen',
					'iso2'     => 'SJ',
					'iso3'     => 'SJM',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'NOK',
						'name'   => 'Norwegian Krone',
						'symbol' => 'kr',
					],
				],
				[
					'name'     => 'Swaziland — Swaziland',
					'iso2'     => 'SZ',
					'iso3'     => 'SWZ',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'SZL',
						'name'   => 'Lilangeni',
						'symbol' => 'E',
					],
				],
				[
					'name'     => 'Sweden — Sverige',
					'iso2'     => 'SE',
					'iso3'     => 'SWE',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'SEK',
						'name'   => 'Swedish krona',
						'symbol' => 'kr',
					],
				],
				[
					'name'     => 'Switzerland — Schweiz',
					'iso2'     => 'CH',
					'iso3'     => 'CHE',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'CHF',
						'name'   => 'Swiss franc',
						'symbol' => 'CHf',
					],
				],
				[
					'name'     => 'Syria — سوريا',
					'iso2'     => 'SY',
					'iso3'     => 'SYR',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'SYP',
						'name'   => 'Syrian pound',
						'symbol' => 'LS',
					],
				],
				[
					'name'     => 'Taiwan — 臺灣',
					'iso2'     => 'TW',
					'iso3'     => 'TWN',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'TWD',
						'name'   => 'New Taiwan dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Tajikistan — Тоҷикистон',
					'iso2'     => 'TJ',
					'iso3'     => 'TJK',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'TJS',
						'name'   => 'Tajikistani somoni',
						'symbol' => 'SM',
					],
				],
				[
					'name'     => 'Tanzania — Tanzania',
					'iso2'     => 'TZ',
					'iso3'     => 'TZA',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'TZS',
						'name'   => 'Tanzanian shilling',
						'symbol' => 'TSh',
					],
				],
				[
					'name'     => 'Thailand — ประเทศไทย',
					'iso2'     => 'TH',
					'iso3'     => 'THA',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'THB',
						'name'   => 'Thai baht',
						'symbol' => '฿',
					],
				],
				[
					'name'     => 'The Bahamas — Bahamas',
					'iso2'     => 'BS',
					'iso3'     => 'BHS',
					'region'   => '',
					'currency' => [
						'code'   => 'BSD',
						'name'   => 'Bahamian dollar',
						'symbol' => 'B$',
					],
				],
				[
					'name'     => 'Togo — Togo',
					'iso2'     => 'TG',
					'iso3'     => 'TGO',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'XOF',
						'name'   => 'West African CFA franc',
						'symbol' => 'CFA',
					],
				],
				[
					'name'     => 'Tokelau — Tokelau',
					'iso2'     => 'TK',
					'iso3'     => 'TKL',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'NZD',
						'name'   => 'New Zealand dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Tonga — Tonga',
					'iso2'     => 'TO',
					'iso3'     => 'TON',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'TOP',
						'name'   => 'Tongan paʻanga',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Trinidad And Tobago — Trinidad and Tobago',
					'iso2'     => 'TT',
					'iso3'     => 'TTO',
					'region'   => '',
					'currency' => [
						'code'   => 'TTD',
						'name'   => 'Trinidad and Tobago dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Tunisia — تونس',
					'iso2'     => 'TN',
					'iso3'     => 'TUN',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'TND',
						'name'   => 'Tunisian dinar',
						'symbol' => 'ت.د',
					],
				],
				[
					'name'     => 'Turkey — Türkiye',
					'iso2'     => 'TR',
					'iso3'     => 'TUR',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'TRY',
						'name'   => 'Turkish lira',
						'symbol' => '₺',
					],
				],
				[
					'name'     => 'Turkmenistan — Türkmenistan',
					'iso2'     => 'TM',
					'iso3'     => 'TKM',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'TMT',
						'name'   => 'Turkmenistan manat',
						'symbol' => 'T',
					],
				],
				[
					'name'     => 'Turks And Caicos Islands — Turks and Caicos Islands',
					'iso2'     => 'TC',
					'iso3'     => 'TCA',
					'region'   => '',
					'currency' => [
						'code'   => 'USD',
						'name'   => 'United States dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Tuvalu — Tuvalu',
					'iso2'     => 'TV',
					'iso3'     => 'TUV',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'AUD',
						'name'   => 'Australian dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Uganda — Uganda',
					'iso2'     => 'UG',
					'iso3'     => 'UGA',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'UGX',
						'name'   => 'Ugandan shilling',
						'symbol' => 'USh',
					],
				],
				[
					'name'     => 'Ukraine — Україна',
					'iso2'     => 'UA',
					'iso3'     => 'UKR',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'UAH',
						'name'   => 'Ukrainian hryvnia',
						'symbol' => '₴',
					],
				],
				[
					'name'     => 'United Arab Emirates — دولة الإمارات العربية المتحدة',
					'iso2'     => 'AE',
					'iso3'     => 'ARE',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'AED',
						'name'   => 'United Arab Emirates dirham',
						'symbol' => 'إ.د',
					],
				],
				[
					'name'     => 'United Kingdom — United Kingdom',
					'iso2'     => 'GB',
					'iso3'     => 'GBR',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'GBP',
						'name'   => 'British pound',
						'symbol' => '£',
					],
				],
				[
					'name'     => 'United States — United States',
					'iso2'     => 'US',
					'iso3'     => 'USA',
					'region'   => '',
					'currency' => [
						'code'   => 'USD',
						'name'   => 'United States dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'United States Minor Outlying Islands — United States Minor Outlying Islands',
					'iso2'     => 'UM',
					'iso3'     => 'UMI',
					'region'   => '',
					'currency' => [
						'code'   => 'USD',
						'name'   => 'United States dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Uruguay — Uruguay',
					'iso2'     => 'UY',
					'iso3'     => 'URY',
					'region'   => 'SA',
					'currency' => [
						'code'   => 'UYU',
						'name'   => 'Uruguayan peso',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Uzbekistan — O‘zbekiston',
					'iso2'     => 'UZ',
					'iso3'     => 'UZB',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'UZS',
						'name'   => 'Uzbekistani soʻm',
						'symbol' => 'лв',
					],
				],
				[
					'name'     => 'Vanuatu — Vanuatu',
					'iso2'     => 'VU',
					'iso3'     => 'VUT',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'VUV',
						'name'   => 'Vanuatu vatu',
						'symbol' => 'VT',
					],
				],
				[
					'name'     => 'Vatican City State (Holy See) — Vaticano',
					'iso2'     => 'VA',
					'iso3'     => 'VAT',
					'region'   => 'EU',
					'currency' => [
						'code'   => 'EUR',
						'name'   => 'Euro',
						'symbol' => '€',
					],
				],
				[
					'name'     => 'Venezuela — Venezuela',
					'iso2'     => 'VE',
					'iso3'     => 'VEN',
					'region'   => 'SA',
					'currency' => [
						'code'   => 'VEF',
						'name'   => 'Bolívar',
						'symbol' => 'Bs',
					],
				],
				[
					'name'     => 'Vietnam — Việt Nam',
					'iso2'     => 'VN',
					'iso3'     => 'VNM',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'VND',
						'name'   => 'Vietnamese đồng',
						'symbol' => '₫',
					],
				],
				[
					'name'     => 'Virgin Islands (British) — British Virgin Islands',
					'iso2'     => 'VG',
					'iso3'     => 'VGB',
					'region'   => '',
					'currency' => [
						'code'   => 'USD',
						'name'   => 'United States dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Virgin Islands (US) — United States Virgin Islands',
					'iso2'     => 'VI',
					'iso3'     => 'VIR',
					'region'   => '',
					'currency' => [
						'code'   => 'USD',
						'name'   => 'United States dollar',
						'symbol' => '$',
					],
				],
				[
					'name'     => 'Wallis And Futuna Islands — Wallis et Futuna',
					'iso2'     => 'WF',
					'iso3'     => 'WLF',
					'region'   => 'OC',
					'currency' => [
						'code'   => 'XPF',
						'name'   => 'CFP franc',
						'symbol' => '₣',
					],
				],
				[
					'name'     => 'Western Sahara — الصحراء الغربية',
					'iso2'     => 'EH',
					'iso3'     => 'ESH',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'MAD',
						'name'   => 'Moroccan Dirham',
						'symbol' => 'MAD',
					],
				],
				[
					'name'     => 'Yemen — اليَمَن',
					'iso2'     => 'YE',
					'iso3'     => 'YEM',
					'region'   => 'AS',
					'currency' => [
						'code'   => 'YER',
						'name'   => 'Yemeni rial',
						'symbol' => '﷼',
					],
				],
				[
					'name'     => 'Zambia — Zambia',
					'iso2'     => 'ZM',
					'iso3'     => 'ZMB',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'ZMW',
						'name'   => 'Zambian kwacha',
						'symbol' => 'ZK',
					],
				],
				[
					'name'     => 'Zimbabwe — Zimbabwe',
					'iso2'     => 'ZW',
					'iso3'     => 'ZWE',
					'region'   => 'AF',
					'currency' => [
						'code'   => 'ZWL',
						'name'   => 'Zimbabwe Dollar',
						'symbol' => '$',
					],
				],
			]
		);
	}
}
